export const enum ErrorTypes {
	userAlreadyExistsError = "userAlreadyExistsError",
	wrongPasswordOrLoginError = "wrongPasswordOrLoginError",
	userNotFoundError = "userNotFoundError",
	productNotFoundError = "productNotFoundError",
	unauthorizedError = "unauthorizedError",
	invalidAuthTokenError = "invalidAuthTokenError",
	invalidUpdateInfoError = "invalidUpdateInfoError",
	forbiddenAccessError = "forbiddenAccessError",
	invalidProductDataError = "invalidProductDataError",
	invalidAuctionDataError = "invalidAuctionDataError",
	productAlreadyTakenError = "productAlreadyTakenError",
	auctionNotFoundError = "auctionNotFoundError",
	auctionSubscriptionError = "auctionSubscriptionError",
}
