name: PR and push CI

on: [pull-request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NPM packages
        run: npm install

      - name: Run eslint check
        run: npm run eslint

      - name: run tests
        run: npm run test

      - name: Run production build
        run: npm run build
