name: pull-request and push

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Switch to source code
        uses: actions/checkout@v2
        
      - name: Switch to current node version
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install NPM packages
        run: npm install

      - name: Run eslint check
        run: npm run eslint

      - name: run tests
        run: npm run test

      - name: Run production build
        run: npm run build:prod
