name: deploy

on:
  push:
    branches:
      - master
      - deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@deployment

      - name: Install NPM packages
        run: npm install

      - name: Run eslint check
        run: npm run eslint

      - name: Run production build
        run: npm run build

